---
title: "Swimming downstream DTE reproducibility"
output: html_notebook
---

## Check the original code: https://github.com/mikelove/swimdown

4 new DTE methods were added to the plot :
 * limmaVoom - as implemented in the paper; uses lengthScaledTPM counts
 * limmaVoomF - like Voom, but filterByExpr() is applied design-aware, which makes it more permissive
 * limmaLogTpm - old LIBD method, without voom() but using log(tpm+0.5)
 * limmaTrend - also using log(tpm+0.5) by with array weights and trend=TRUE

```{r check salmon}
## from https://github.com/mikelove/swimdown/blob/850b442098ba3bac2ecd303fc283982b31971232/simulate/plot_tpms.R
ftxi='sdownstream/txi.rda' ## scaled counts
frawtxi='sdownstream/txi_raw.rda' ## unscaled, raw counts

n <- 12
sample <- paste0(rep(1:n,2),"_",rep(1:2,each=n))
if (!file.exists(ftxi) | !file.exists(frawtxi)) {
  library(tximport)
  files <- file.path('salmon', sample,'quant.sf')
  names(files) <- sample
  txi.raw <- tximport(files,type='salmon', txOut=TRUE, varReduce=TRUE)
  save(txi.raw, file=ftxi)
  txi <- tximport(files,type='salmon', txOut=TRUE, 
                  countsFromAbundance="lengthScaledTPM", varReduce=TRUE)
  save(txi, file=frawtxi)
}
```


```{r}
load(ftxi) # loads txi
load(frawtxi) #loads txi.raw for DESeq2 only
r <- load('sdownstream/simulate.rda')
suppressPackageStartupMessages({
  library(tximport)
  library(DESeq2)
  library(limma)
  library(edgeR)
  library(samr)
  library(iCOBRA)
  library(ggplot2)
})

source('dte_plots.R')

n=12
n.sub=12

idx <- c(1:n.sub, n + 1:n.sub)

source("dte_funcs.R")
```


```{r}
 
 padj <- data.frame(row.names=rownames(txi$counts))
 ## limma-voom
 st <- system.time({ 
    tt <- limmavoom(txi$counts[,idx], n.sub)
  })
 padj$limmaVoom <- tt$adj.P.Val[match(rownames(padj), rownames(tt))]

 ## limma-voom with more permissive expression filter
 st <- system.time({ 
    tt <- limmavoom.ftx(txi$counts[,idx], n.sub)
  })
 padj$limmaVoomF <- tt$adj.P.Val[match(rownames(padj), rownames(tt))]

 ## limma-logTPM - the old LIBD approach, using log(tpm+0.5)
 st <- system.time({ 
    tt <- limmalogtpm(txi$abundance[,idx], n.sub)
  })
 padj$limmaLogTpm <- tt$adj.P.Val[match(rownames(padj), rownames(tt))]

 ## limma-logTPM - the old LIBD approach, using log(tpm+0.5)
 st <- system.time({ 
    tt <- limmatrend(txi$abundance[,idx], n.sub)
  })
 padj$limmaTrend <- tt$adj.P.Val[match(rownames(padj), rownames(tt))]

 ## edgeR
 st <- system.time({ 
    tt <- edger(txi$counts[,idx], n.sub)
  })
 padj$edgeR <- tt$FDR[match(rownames(padj), rownames(tt))]

 ## edgeR-QL
 st <- system.time({ 
    tt <- edgerQL(txi$counts[,idx], n.sub)
  })
 padj$edgeR.QL <- tt$FDR[match(rownames(padj), rownames(tt))]
 
 ## DESeq2 
 st <- system.time({
    res <- deseq2(txi.raw, n.sub)
  })
 padj$DESeq2 <- res$padj[match(rownames(padj), rownames(res))]
```

```{r iCobra}
  iso.any <- iso.dtu | iso.dte | iso.dge
  status <- as.numeric(rownames(padj) %in% names(iso.dtu)[iso.any])
  cd <- COBRAData(padj=padj,
                  truth=data.frame(status, row.names=rownames(padj)))
  pdf(file=paste0("dte_n",n.sub,".pdf"))
  print(myicobra(cd, "Transcript"))
  dev.off()

  pdf(file=paste0("dte_fdrbkd_",n.sub,".pdf"), width=9)
  fdrBreakdownTxp(padj, alpha=.05)
  dev.off()
```

